- name: Ensure {{ conf_dir }} exists
  file: path={{ conf_dir }} state=directory

- name: Ensure {{ log_dir }} exists
  file: path={{ log_dir }} state=directory

- name: Upload dequeuer configuration
  template:
    src: config/dequeuer.env
    dest: "{{ conf_dir }}/dequeuer.env"
    owner: root
    group: root
    mode: 0644

# - name: Kill running process
#   shell: "ps -ef | grep -v grep | grep -w {{ PROCESS }} | awk '{print $2}'"
#   register: running_processes    

- name: Set crontab job
  cron:
    job: '
      bash -c ''
        source {{ conf_dir }}/dequeuer.env;
        cd {{ base_path }}/scripts && ./run_dequeuer.sh
        >> {{ log_dir }}/dequeuer.log 2>&1 &
      ''
      '
    state: present
    name: dequeuer_musk
    minute: "*"