version: 1
disable_existing_loggers: True
formatters:
  simple:
    format: '%(asctime)s - %(process)d - %(message)s'
    datefmt: '%b %d %H:%M:%S'
handlers:
  console:
    class: logging.StreamHandler
    formatter: simple
    stream: ext://sys.stdout
root:
  level: DEBUG
  handlers: [console]